// errors
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

// authentication
export const START_AUTHENTICATING = 'START_AUTHENTICATING'
export const STOP_AUTHENTICATING = 'STOP_AUTHENTICATING'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// Local Department
export const GET_LOCALDEPTS = 'GET_LOCALDEPTS'
export const GET_LOCALDEPT = 'GET_LOCALDEPT'
export const LOADING_LOCALDEPT = 'LOADING_LOCALDEPT'
export const LOADING_LOCALDEPT_END = 'LOADING_LOCALDEPT_END'

// Application Management
export const GET_APPS_LOCAL = 'GET_APPS_LOCAL'
export const GET_APP_LOCAL = 'GET_APP_LOCAL'
export const GET_APPS_LOCAL_FARMER = 'GET_APPS_LOCAL_FARMER'
export const GET_APP_LOCAL_FARMER = 'GET_APP_LOCAL_FARMER'
export const GET_APPS_LOCAL_COMPANY = 'GET_APPS_LOCAL_COMPANY'
export const GET_APP_LOCAL_COMPANY = 'GET_APP_LOCAL_COMPANY'
export const APPROVE_APP_LOCAL_FARMER = 'APPROVE_APP_LOCAL_FARMER'
export const RETURN_APP_LOCAL_FARMER = 'RETURN_APP_LOCAL_FARMER'
export const LOADING_APPLICATION = 'LOADING_APPLICATION'
export const LOADING_APPLICATION_END = 'LOADING_APPLICATION_END'

// Bale Management
export const GET_BALES_LOCAL = 'GET_BALES_LOCAL'
export const GET_BALES_LOCAL_FARMER = 'GET_BALES_LOCAL_FARMER'
export const GET_BALES_LOCAL_FARMER_PILJI = 'GET_BALES_LOCAL_FARMER_PILJI'
export const GET_BALE_LOCAL_FARMER_PILJI = 'GET_BALE_LOCAL_FARMER_PILJI'
export const GET_BALES_LOCAL_COMPANY = 'GET_BALES_LOCAL_COMPANY'
export const GET_BALES_LOCAL_COMPANY_PILJI = 'GET_BALES_LOCAL_COMPANY_PILJI'
export const GET_BALE_LOCAL_COMPANY_PILJI = 'GET_BALE_LOCAL_COMPANY_PILJI'
export const LOADING_BALE = 'LOADING_BALE'
export const LOADING_BALE_END = 'LOADING_BALE_END'

// Company Management
export const GET_COMPANIES = 'GET_COMPANIES'
export const GET_COMPANY = 'GET_COMPANY'
export const ADD_COMPANY = 'ADD_COMPANY'
export const MODIFY_COMPANY = 'MODIFY_COMPANY'
export const DELETE_COMPANY = 'DELETE_COMPANY'
export const LOADING_COMPANY = 'LOADING_COMPANY'
export const LOADING_COMPANY_END = 'LOADING_COMPANY_END'

// balers
export const GET_BALERS = 'GET_BALERS'
export const GET_BALER = 'GET_BALER'
export const ADD_BALER = 'ADD_BALER'
export const MODIFY_BALER = 'MODIFY_BALER'
export const DELETE_BALER = 'DELETE_BALER'
export const LOADING_BALER = 'LOADING_BALER'
export const LOADING_BALER_END = 'LOADING_BALER_END'
